openapi: 3.0.1
info:
  title: Testkube API
  description: >-
    Testkube provides a Kubernetes-native framework for test definition,
    execution and results
  contact:
    email: testkube@kubeshop.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
paths:
  /executors:
    get:
      summary: List executors
      description: List executors available in cluster
      operationId: listExecutors
      parameters:
        - $ref: './components.yaml#/components/parameters/Selector'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Executor'
            text/yaml:
              schema:
                type: string
        '400':
          description: problem with input for CRD generation
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    post:
      summary: Create new executor
      description: Create new executor based on variables passed in request
      operationId: createExecutor
      requestBody:
        description: executor request body data
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutorUpsertRequest'
          text/yaml:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            text/yaml:
              schema:
                type: string
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ExecutorDetails'
        '400':
          description: >-
            problem with executor definition - probably some bad input occurs
            (invalid JSON body or similar)
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with communicating with kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    delete:
      summary: Delete executors
      description: Deletes labeled executors
      operationId: deleteExecutors
      parameters:
        - $ref: './components.yaml#/components/parameters/Selector'
      responses:
        '204':
          description: no content
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
  /executors/{id}:
    delete:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
      summary: Delete executor
      description: Deletes executor by its name
      operationId: deleteExecutor
      responses:
        '204':
          description: executor deleted successfuly
        '502':
          description: problem with communicating with kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    get:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
      summary: Get executor details
      description: Returns executors data with executions passed to executor
      operationId: getExecutor
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ExecutorDetails'
            text/yaml:
              schema:
                type: string
        '400':
          description: problem with input for CRD generation
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: problem with getting executor data
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with communicating with kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    patch:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
      summary: Update executor
      description: Update new executor based on variables passed in request
      operationId: updateExecutor
      requestBody:
        description: executor request body data
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutorUpdateRequest'
          text/yaml:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ExecutorDetails'
        '400':
          description: >-
            problem with executor definition - probably some bad input occurs
            (invalid JSON body or similar)
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '404':
          description: executor not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with communicating with kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
