openapi: 3.0.1
info:
  title: Testkube Pro API
  description: API for Testkube Pro
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: enterprise-api/1.10.7
paths:
  /users:
    get:
      summary: List users
      description: List users
      operationId: listUsers
      parameters:
        - $ref: './components.yaml#/components/parameters/Limit'
      responses:
        '200':
          $ref: './components.yaml#/components/responses/Users'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './components.yaml#/components/responses/ForbiddenError'
      security:
        - BearerAuth: []
    post:
      summary: Create new user
      description: Create user
      operationId: createUser
      requestBody:
        $ref: './components.yaml#/components/requestBodies/User'
      responses:
        '200':
          $ref: './components.yaml#/components/responses/User'
        '400':
          $ref: './components.yaml#/components/responses/BadRequestError'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './components.yaml#/components/responses/ForbiddenError'
      security:
        - BearerAuth: []
  /users/{id}:
    get:
      summary: Get user by ID
      description: Get user by ID
      operationId: getUser
      responses:
        '200':
          $ref: './components.yaml#/components/responses/User'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './components.yaml#/components/responses/ForbiddenError'
      security:
        - BearerAuth: []
    delete:
      summary: Delete user
      description: Deletes user
      operationId: deleteUser
      responses:
        '204':
          $ref: './components.yaml#/components/responses/NoContent'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './components.yaml#/components/responses/ForbiddenError'
      security:
        - BearerAuth: []
    patch:
      summary: Update user
      description: Update user with given request body
      operationId: updateUser
      requestBody:
        $ref: './components.yaml#/components/requestBodies/User'
      responses:
        '200':
          $ref: './components.yaml#/components/responses/User'
        '400':
          $ref: './components.yaml#/components/responses/BadRequestError'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '403':
          $ref: './components.yaml#/components/responses/ForbiddenError'
      security:
        - BearerAuth: []
    parameters:
      - $ref: './components.yaml#/components/parameters/ID'
