openapi: 3.0.1
info:
  title: Testkube Pro API
  description: API for Testkube Pro
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: enterprise-api/1.10.14
paths:
  /health:
    get:
      summary: Healthcheck
      description: Get healthcheck status and information
      operationId: healthcheck
      responses:
        '200':
          $ref: './components.yaml#/components/responses/Healthcheck'
