openapi: 3.0.1
info:
  title: Testkube Pro API
  description: API for Testkube Pro
  contact:
    email: testkube@kubeshop.io
  license:
    name: COMMERICAL
    url: https://opensource.org/licenses/MIT
  version: cloud-api/1.10.51
servers:
  - url: https://api.testkube.io
    description: Testkube Cloud API Endpoint
  - url: https://<your-testkube-api-host>
    description: Testkube On-Prem API Endpoint
paths:
  /organizations/invites/{inviteID}/accept:
    get:
      summary: Accept email invite
      description: accept email invite
      operationId: acceptOrganizationEmailInvite
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  org:
                    type: string
                required:
                  - org
        '400':
          $ref: './components.yaml#/components/responses/BadRequestError'
        '401':
          $ref: './components.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './components.yaml#/components/responses/NotFoundError'
      deprecated: true
      security:
        - BearerAuth: []
    parameters:
      - $ref: './components.yaml#/components/parameters/InviteID'
