openapi: 3.0.1
info:
  title: Testkube API
  description: >-
    Testkube provides a Kubernetes-native framework for test definition,
    execution and results
  contact:
    email: testkube@kubeshop.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
  - url: https://api.testkube.io
    description: Testkube Cloud API Endpoint
  - url: https://<your-testkube-api-host>
    description: Testkube On-Prem API Endpoint
paths:
  /tests:
    get:
      summary: List tests
      description: List available tests
      operationId: listTests
      parameters:
        - $ref: './components.yaml#/components/parameters/Selector'
        - $ref: './components.yaml#/components/parameters/TextSearch'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Test'
            text/yaml:
              schema:
                type: string
        '400':
          description: invalid parameters
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    post:
      summary: Create new test
      description: Create new test based on file content, uri or git based data
      operationId: createTest
      requestBody:
        description: test details body
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/TestUpsertRequest'
          text/yaml:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            text/yaml:
              schema:
                type: string
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Test'
        '400':
          description: >-
            problem with test definition - probably some bad input occurs
            (invalid JSON body or similar)
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with communicating with kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    delete:
      summary: Delete tests
      description: Deletes all or labeled tests
      operationId: deleteTests
      parameters:
        - $ref: './components.yaml#/components/parameters/Selector'
      responses:
        '204':
          description: no content
        '404':
          description: no tests found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: problem with deleting tests and their executions
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
  /tests/{id}:
    patch:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
      summary: Update test
      description: Update test based on test content or git based data
      operationId: updateTest
      requestBody:
        description: test details body
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/TestUpdateRequest'
          text/yaml:
            schema:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Test'
        '400':
          description: >-
            problem with test definition - probably some bad input occurs
            (invalid JSON body or similar)
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '404':
          description: test not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with communicating with kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    get:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
      summary: Get test
      description: Gets the specified test
      operationId: getTest
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Test'
            text/yaml:
              schema:
                type: string
        '400':
          description: invalid parameters
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '404':
          description: test not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    delete:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
        - $ref: './components.yaml#/components/parameters/SkipDeleteExecutions'
        - $ref: './components.yaml#/components/parameters/SkipDeleteCRD'
      summary: Delete test
      description: Deletes a test
      operationId: deleteTest
      responses:
        '204':
          description: no content
        '404':
          description: no tests found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: problem with deleting test and its executions
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
  /tests/{id}/abort:
    post:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
      summary: Abort all executions of a test
      description: Abort all test executions
      operationId: abortTestExecutions
      responses:
        '204':
          description: no content
        '404':
          description: no execution found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: problem with aborting test execution
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
  /tests/{id}/metrics:
    get:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
        - $ref: './components.yaml#/components/parameters/LastNDays'
        - $ref: './components.yaml#/components/parameters/Limit'
      summary: Get test metrics
      description: >-
        Gets test metrics for given tests executions, with particular execution
        status and timings
      operationId: getTestMetrics
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ExecutionsMetrics'
        '500':
          description: problem with getting metrics
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with read information from storage
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
  /tests/{id}/executions:
    post:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
        - $ref: './components.yaml#/components/parameters/Namespace'
        - $ref: './components.yaml#/components/parameters/TestExecutionName'
      summary: Starts new test execution
      description: >-
        New test execution returns new execution details on successful execution
        start
      operationId: executeTest
      requestBody:
        description: body passed to configure execution
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/ExecutionRequest'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ExecutionResult'
        '400':
          description: problem with request body
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '404':
          description: test not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: problem with test execution
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with communicating with kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    get:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
        - $ref: './components.yaml#/components/parameters/LastNDays'
        - $ref: './components.yaml#/components/parameters/PageSize'
        - $ref: './components.yaml#/components/parameters/PageIndex'
        - $ref: './components.yaml#/components/parameters/ExecutionsStatusFilter'
        - $ref: './components.yaml#/components/parameters/StartDateFilter'
        - $ref: './components.yaml#/components/parameters/EndDateFilter'
      summary: Get all test executions
      description: Returns array of all available test executions
      operationId: listTestExecutions
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ExecutionsResult'
        '404':
          description: test or execution not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: problem with getting test executions from storage
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
  /tests/{id}/executions/{executionID}:
    get:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
        - $ref: './components.yaml#/components/parameters/executionID'
      summary: Get test execution
      description: Returns execution with given executionID
      operationId: getTestExecution
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/Execution'
        '404':
          description: execution not found
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '500':
          description: problem with getting test executions from storage
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
        '502':
          description: problem with reading secrets from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
    patch:
      parameters:
        - $ref: './components.yaml#/components/parameters/ID'
        - $ref: './components.yaml#/components/parameters/executionID'
      summary: Aborts execution
      description: Aborts execution with given executionID
      operationId: abortExecution
      responses:
        '204':
          description: no content
        '502':
          description: problem with read information from kubernetes cluster
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: './components.yaml#/components/schemas/Problem'
