name: Update image inventory

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint-images:
    name: Update image inventory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh

      - name: Update image inventory documentation
        run: bash ./image.sh
        working-directory: ./scripts

      - name: Commit the updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update image inventory"
          branch: main
